[project]
name = "auroral_processing"
version = "0.1.0" 
requires-python = ">=3.11"
dependencies = [
    "numpy",
    "h5py",
    "matplotlib",
    "pillow",
    "tqdm",
    "imageio[ffmpeg]",
    "pandas",
]
authors = [
    { name = "Michael Lavender", email = "michaelzlavender@gmail.com" },
]


[project.optional-dependencies]
dmc = ["histutils @ git+https://github.com/space-physics/histutils.git"]
themis = ["pyaurorax"]
flow = ["opencv-python", "openpiv"]

[build-system]
requires = ["setuptools>=64"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
include = ["auroral_processing*"]


